export const INTERNAL_ERROR_RESPONSE_CODE = 500;
export const BAD_REQUEST_RESPONSE_CODE = 400;
export const UNAUTHORIZED_RESPONSE_CODE = 401;
export const FORBIDDEN_RESPONSE_CODE = 403;
export const NOT_FOUND_RESPONSE_CODE = 404;
export const SUCCESS_RESPONSE_CODE = 200;
